# This file is used by the Packit service.
# Currently it is used for the gating of pull requests.
#
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# We need a specfile to build the RPM package.
# But instead of storing it in this repository,
# we use the one that exists already in src.fedoraproject.org/rpms/golang.
# In particular, we use the specfile from the branch `eln`.
# We'll create the temporary folder .packit_rpm to store the content of the
# Fedora repository.
specfile_path: .packit_rpm/golang.spec

# We need to tell Packit which files to sync from the upstream repository.
files_to_sync:
    - .packit.yaml
    - src: .packit_rpm/golang.spec
      dest: golang.spec

# The name of the package in the upstream repository.
upstream_package_name: golang
# The name of the package in Fedora.
downstream_package_name: golang
# Use a different tag template for the upstream repository.
upstream_tag_template: "v{version}"

actions:
    post-upstream-clone:
        # Use the Fedora ELN specfile.
        - "git clone https://src.fedoraproject.org/rpms/golang.git .packit_rpm --branch eln"
        # We're not in dist-git, so remove the sources file.
        - "rm -fv .packit_rpm/sources"
        # We'll probably need to drop the patches inside the specfile.

jobs:
  # Build the package in Fedora ELN when a pull request is opened.
  # It can be requested by adding a comment with the text: /packit copr-build
  # This will run the job in the Copr project `alexsaezm/golang-fips`.
- job: copr_build
  trigger: pull_request
  owner: alexsaezm
  project: go-fips
  targets:
  - fedora-eln-aarch64
  - fedora-eln-ppc64le
  - fedora-eln-s390x
  - fedora-eln-x86_64
